export const CREATE_AUCTION = "CREATE_AUCTION";
export const LOAD_AUCTION_SUCCESS = "LOAD_AUCTION_SUCCESS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";

export const CREATE_BID = "CREATE_BID";
export const LOAD_BID_SUCCESS = "LOAD_BID_SUCCESS";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_ITEMS_SUCCESS = "LOAD_ITEMS_SUCCESS";

export const PROCESS_BID_ITEM = "PROCESS_BID_ITEM";
export const LOAD_SOLD_ITEM_SUCCESS = "LOAD_SOLD_ITEM_SUCCESS";